name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: module
    attributes:
      label: Target Module
      description: Which module would this feature affect?
      options:
        - API (Backend)
        - Web (Frontend)
        - Both
        - Database
        - Build/CI
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        Example: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: |
        Describe alternatives you've considered and why they don't work as well.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Any thoughts on how this could be implemented?
      placeholder: |
        Optional: Share your ideas on how this feature could be built.
        - API endpoints needed
        - UI components
        - Database changes
        - etc.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or mockups
      placeholder: Add any other context, screenshots, or examples here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: false
        - label: I am willing to help implement this feature
          required: false
