export enum StockMovementReason {
  PURCHASE_RECEIVE = 'PURCHASE_RECEIVE',
  SALE = 'SALE',
  WASTE = 'WASTE',
  DAMAGED = 'DAMAGED',
  EXPIRED = 'EXPIRED',
  COUNT_CORRECTION = 'COUNT_CORRECTION',
  RETURN_FROM_CLIENT = 'RETURN_FROM_CLIENT',
  RETURN_TO_SUPPLIER = 'RETURN_TO_SUPPLIER',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
}
